version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    ports:
      - 8000:80
    command: php -S 0.0.0.0:80 -t /var/www/html
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
